name: Deploy CloudFormation Stacks

on:
  push: 
    branches: "main"
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - ".github"
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cluster:
    name: Deploy stack 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }} 

      - name: Deploy CloudFormation Stacks
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name:  hgbuckets
          template: template.yaml
          capabilities: CAPABILITY_NAMED_IAM
